const fs = require('fs');
const vm = require('vm');
const assert = require('assert/strict');
const context = vm.createContext({});
vm.runInContext(fs.readFileSync('public/deductions.js', 'utf8'), context);
const find = context.findTuple;
const board = () => Array.from({length:81}, () => []);
let map = board();
map[0] = [2,7]; map[1] = [2,7]; map[2] = [2,3,7,9];
let result = find(map);
assert.equal(result.size, 2);
assert.equal(result.unit, 'row 1');
assert.equal(JSON.stringify(result.removals), JSON.stringify([{cell:2,digit:2},{cell:2,digit:7}]));
map = board();
map[0] = [1,2]; map[9] = [2,3]; map[18] = [1,3]; map[27] = [1,3,4,5];
result = find(map);
assert.equal(result.size,3);
assert.equal(result.unit,'column 1');
assert.equal(result.removals.length,2);
map = board();
map[0] = [2,7]; map[10] = [2,7]; map[20] = [2,3,7,9];
assert.equal(find(map).unit,'box 1');
map = board(); map[0] = [1,2]; map[1] = [2,3]; map[2] = [3,4]; map[3] = [1,2,3,4,5];
assert.equal(find(map),null,'Four possible digits cannot form a triple');
map = board(); map[0] = [2,7]; map[1] = [2,7];
assert.equal(find(map),null,'A tuple with nothing to eliminate is not useful');
console.log('PASS: naked pairs, triples, row/column/box, invalid unions, and no-op deductions.');
